language: node_js
node_js:
  - node
dist: bionic
sudo: required

branches:
  only:
   - master
before_script:
  - npm install -g @angular/cli

script:
  # - ng lint
  # - npm run test-headless
  - ng build --prod --base-href https://carine18.github.io/assessment1/
 
#  notifications:  
#   email:  
#     recipients:  
#    
#     on_success: always  
#     on_failure: always

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist/assessment1
  on:
    branch: master

